# Updated for Discord auth testing - October 18, 2025
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  # Allow Discord Client ID and Redirect URI in build output (these are not secrets)
  SECRETS_SCAN_OMIT_KEYS = "VITE_DISCORD_CLIENT_ID,VITE_DISCORD_REDIRECT_URI"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
